databases:
  - name: nova-db
    plan: free
    databaseName: nova
    user: nova

services:
  - type: web
    name: nova-ecommerce
    plan: free
    runtime: python
    buildCommand: "bash build.sh"
    startCommand: "gunicorn apple_store.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nova-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"